#https://www.home-assistant.io/components/input_number

#dummy_number_1:
#  name: Slider
#  initial: 30
#  min: 0
#  max: 86340
#  step: 300
#  mode: slider
#dummy_number_2:
#  name: Numeric Input Box
#  initial: 30
#  min: -20
#  max: 35
#  step: 1
#  mode: box

google_home_volume:
  name: Volume
  icon: mdi:volume-high
  min: 0
  max: 1
  step: 0.1
  mode: slider

tv_remote_channel:
  name: Canale
  icon: mdi:numeric
  min: 1
  max: 999
  step: 1
  mode: box

event_volume_sveglia_1:
  name: Volume
  icon: mdi:volume-high
  min: 0
  max: 1
  step: 0.1
  mode: slider

event_volume_sveglia_2:
  name: Volume
  icon: mdi:volume-high
  min: 0
  max: 1
  step: 0.1
  mode: slider

event_volume_ale_letto:
  name: Volume
  icon: mdi:volume-high
  min: 0
  max: 1
  step: 0.1
  mode: slider

event_volume_ale_scuola:
  name: Volume
  icon: mdi:volume-high
  min: 0
  max: 1
  step: 0.1
  mode: slider

event_volume_sonoleore:
  name: Volume
  icon: mdi:volume-high
  min: 0
  max: 1
  step: 0.1
  mode: slider

event_charge_level_smartplug_1:
  name: Livello Batteria (%)
  icon: mdi:battery-low
  min: 5
  max: 95
  step: 1
  mode: box
event_charge_level_smartplug_2:
  name: Livello Batteria (%)
  icon: mdi:battery-low
  min: 5
  max: 95
  step: 1
  mode: box
event_charge_level_smartplug_3:
  name: Livello Batteria (%)
  icon: mdi:battery-low
  min: 5
  max: 95
  step: 1
  mode: box
event_charge_level_smartplug_4:
  name: Livello Batteria (%)
  icon: mdi:battery-low
  min: 5
  max: 95
  step: 1
  mode: box
event_charge_level_smartplug_5:
  name: Livello Batteria (%)
  icon: mdi:battery-low
  min: 5
  max: 95
  step: 1
  mode: box
event_charge_level_smartplug_6:
  name: Livello Batteria (%)
  icon: mdi:battery-low
  min: 5
  max: 95
  step: 1
  mode: box
event_charge_level_smartplug_7:
  name: Livello Batteria (%)
  icon: mdi:battery-low
  min: 5
  max: 95
  step: 1
  mode: box
event_charge_level_smartplug_8:
  name: Livello Batteria (%)
  icon: mdi:battery-low
  min: 5
  max: 95
  step: 1
  mode: box
event_charge_level_sonoff_basic_1:
  name: Livello Batteria (%)
  icon: mdi:battery-low
  min: 5
  max: 95
  step: 1
  mode: box
event_charge_level_sonoff_basic_2:
  name: Livello Batteria (%)
  icon: mdi:battery-low
  min: 5
  max: 95
  step: 1
  mode: box

event_duration_cover_up:
  name: Durata
  icon: mdi:timer-sand
  unit_of_measurement: sec.
  min: 1
  max: 15
  step: 1
  mode: box
event_duration_cover_down:
  name: Durata
  icon: mdi:timer-sand
  unit_of_measurement: sec.
  min: 1
  max: 15
  step: 1
  mode: box
event_afterdawn_cover_up:
  name: Dopo Alba
  icon: mdi:timer-sand
  unit_of_measurement: min.
  min: 0
  max: 120
  step: 1
  mode: box
event_aftersunset_cover_down:
  name: Dopo Tramonto
  icon: mdi:timer-sand
  unit_of_measurement: min.
  min: 0
  max: 120
  step: 1
  mode: box

irrigation_zone1_minutes:
  name: Zona 1
  icon: mdi:numeric-1-box-outline
  unit_of_measurement: min.
  min: 0
  max: 60
  step: 1
  mode: box
irrigation_zone2_minutes:
  name: Zona 2
  icon: mdi:numeric-2-box-outline
  unit_of_measurement: min.
  min: 0
  max: 60
  step: 1
  mode: box
irrigation_zone3_minutes:
  name: Zona 3
  icon: mdi:numeric-3-box-outline
  unit_of_measurement: min.
  min: 0
  max: 60
  step: 1
  mode: box
irrigation_nextstart_in_days:
  name: Prossimo avvio tra
  icon: mdi:calendar-month
  unit_of_measurement: giorni
  min: 1
  max: 7
  step: 1
  mode: box
