#https://www.home-assistant.io/components/input_text

#dummy_text_2:
#  name: Text 2
#  min: 5
#  max: 10
#dummy_text_3:
#  name: Text 3
#  pattern: "[a-fA-F0-9]*"
#dummy_text_4:
#  name: Text 4
#  mode: password

hass_theme_selected_saved:
  name: Selected Theme
  icon: mdi:theme-light-dark

event_ale_letto:
  name: Avviso
  icon: mdi:comment-alert-outline

event_ale_scuola:
  name: Avviso
  icon: mdi:comment-alert-outline

event_sveglia_1:
  name: Avviso
  icon: mdi:comment-alert-outline

event_sveglia_2:
  name: Avviso
  icon: mdi:comment-alert-outline

speak_generic_msg:
  name: Messaggio
  icon: mdi:comment-text-outline

tts_last_sentence:
  name: Last TTS message
  icon: mdi:comment-text-outline

webhook_last_script:
  name: Last script (via webhook)
  icon: mdi:script-text-outline

mqtt_last_service:
  name: Last service (via MQTT)
  icon: mdi:script-text-outline

switch_name_sonoff_basic_1:
  name: Sonoff Basic 1 - Name
  icon: mdi:dip-switch
switch_icon_sonoff_basic_1:
  name: Sonoff Basic 1 - Icon
  icon: mdi:star-box

switch_name_sonoff_basic_2:
  name: Sonoff Basic 2 - Name
  icon: mdi:dip-switch
switch_icon_sonoff_basic_2:
  name: Sonoff Basic 2 - Icon
  icon: mdi:star-box

switch_name_sonoff_basic_3:
  name: Sonoff Basic 3 - Name
  icon: mdi:dip-switch
switch_icon_sonoff_basic_3:
  name: Sonoff Basic 3 - Icon
  icon: mdi:star-box

switch_name_smartplug_1:
  name: Smart Plug 1 - Name
  icon: mdi:dip-switch
switch_icon_smartplug_1:
  name: Smart Plug 1 - Icon
  icon: mdi:star-box

switch_name_smartplug_2:
  name: Smart Plug 2 - Name
  icon: mdi:dip-switch
switch_icon_smartplug_2:
  name: Smart Plug 2 - Icon
  icon: mdi:star-box

switch_name_smartplug_3:
  name: Smart Plug 3 - Name
  icon: mdi:dip-switch
switch_icon_smartplug_3:
  name: Smart Plug 3 - Icon
  icon: mdi:star-box

switch_name_smartplug_4:
  name: Smart Plug 4 - Name
  icon: mdi:dip-switch
switch_icon_smartplug_4:
  name: Smart Plug 4 - Icon
  icon: mdi:star-box

switch_name_smartplug_5:
  name: Smart Plug 5 - Name
  icon: mdi:dip-switch
switch_icon_smartplug_5:
  name: Smart Plug 5 - Icon
  icon: mdi:star-box

switch_name_smartplug_6:
  name: Smart Plug 6 - Name
  icon: mdi:dip-switch
switch_icon_smartplug_6:
  name: Smart Plug 6 - Icon
  icon: mdi:star-box

switch_name_smartplug_7:
  name: Smart Plug 7 - Name
  icon: mdi:dip-switch
switch_icon_smartplug_7:
  name: Smart Plug 7 - Icon
  icon: mdi:star-box

switch_name_smartplug_8:
  name: Smart Plug 8 - Name
  icon: mdi:dip-switch
switch_icon_smartplug_8:
  name: Smart Plug 8 - Icon
  icon: mdi:star-box
