# Use this file to store secrets like usernames and passwords.
#https://home-assistant.io/docs/configuration/secrets/

# base_url: -secret-

home_latitude: -secret-
home_longitude: -secret-

#Log Severities: -secret-
log_default: -secret-

router_fritzbox_ip: -secret-
router_fritzbox_user: -secret-
router_fritzbox_pwd: -secret-

nas_ip: -secret-
nas_port: -secret-
nas_admin_user: -secret-
nas_admin_pwd: -secret-

# duckdns_domain: -secret-
# duckdns_token: -secret-

mqtt_broker: -secret-
mqtt_port: -secret-
mqtt_user: -secret-
mqtt_pwd: -secret-

telegram_api: -secret-
#telegram_api: -secret-
telegram_chatid_paolo: -secret-
telegram_chatid_silvia: -secret-

ifttt_key: -secret-

samsung_tv_ip: -secret-
cell_paolo_ip: -secret-
cell_silvia_ip: -secret-
tablet_ale1_ip: -secret-
tablet_ale2_ip: -secret-
tablet_paolo_ip: -secret-
google_home_ip: -secret-
google_chromecast_ip: -secret-
smartplug_3_ip: -secret-
xiaomi_gateway_ip: -secret-
epson_printer_ip: -secret-
prusa_3d_printer_ip: -secret-

pi_hole_host: -secret-

maps_api_key: -secret-

tuya_country_code: -secret-
tuya_user: -secret-
tuya_pwd: -secret-

darksky_api_key: -secret-

xiaomi_gateway_key: -secret-

openuv_api_key: -secret-

github_hacs: -secret-
