# Use this file to store secrets like usernames and passwords.
#https://home-assistant.io/docs/configuration/secrets/

# base_url: -secret-

#Zone - Home
zone_home_name: -secret-
zone_home_lat: -secret-
zone_home_long: -secret-
#Zone - Work Paolo
zone_workpaolo_name: -secret-
zone_workpaolo_lat: -secret-
zone_workpaolo_long: -secret-
#Zone - Work Silvia
zone_worksilvia_name: -secret-
zone_worksilvia_lat: -secret-
zone_worksilvia_long: -secret-
#Zone - Grandparents
zone_grandparents_name: -secret-
zone_grandparents_lat: -secret-
zone_grandparents_long: -secret-

#Log Severities: -secret-
log_default: -secret-

hass_api_llt: -secret-

fritzbox_router_ip: -secret-
fritzbox_repeater_ip: -secret-

nas_ip: -secret-
nas_port: -secret-
nas_admin_user: -secret-
nas_admin_pwd: -secret-

# duckdns_domain: -secret-
# duckdns_token: -secret-

mqtt_broker: -secret-
mqtt_port: -secret-
mqtt_user: -secret-
mqtt_pwd: -secret-

telegram_api: -secret-
#telegram_api: -secret-
telegram_chatid_paolo: -secret-
telegram_chatid_silvia: -secret-

db_url: -secret-

samsung_tv_ip: -secret-
cell_paolo_ip: -secret-
cell_silvia_ip: -secret-
tablet_ale_ip: -secret-
tablet_ale_scuola_ip: -secret-
tablet_silvia_ip: -secret-
tablet_paolo_ip: -secret-
google_homemini_salotto_ip: -secret-
google_nesthub_cucina_ip: -secret-
google_speaker_studio_ip: -secret-
google_chromecast_ip: -secret-
smartplug_3_ip: -secret-
epson_printer_ip: -secret-
prusa_3d_printer_ip: -secret-
landroid_ip: -secret-

maps_api_key: -secret-

darksky_api_key: -secret-

github_hacs: -secret-

octoprint_host: -secret-
octoprint_api_key: -secret-

landroid_user: -secret-
landroid_pwd: -secret-
landroid_id: -secret-

sonoff_user: -secret-
sonoff_pwd: -secret-
