#https://www.home-assistant.io/components/binary_sensor

- platform: template  #https://www.home-assistant.io/components/binary_sensor.template
  sensors:
    online_adguard:
      friendly_name: AdGuard
      icon_template: mdi:shield-half-full
      device_class: connectivity
      value_template: "{{ not is_state('sensor.adguard_dns_queries', 'unavailable') and not is_state('sensor.adguard_dns_queries', 'unknown') }}"
    online_sonoff_basic_1:
      friendly_name: Sonoff Basic 1
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.sonoff_basic_1', 'unavailable') and not is_state('switch.sonoff_basic_1', 'unknown') }}"
    online_sonoff_basic_2:
      friendly_name: Sonoff Basic 2
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.sonoff_basic_2', 'unavailable') and not is_state('switch.sonoff_basic_2', 'unknown') }}"
    online_sonoff_basic_3:
      friendly_name: Sonoff Basic 3
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.sonoff_basic_3', 'unavailable') and not is_state('switch.sonoff_basic_3', 'unknown') }}"
    online_sonoff_dual_1:
      friendly_name: Sonoff Dual
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.sonoff_dual_1', 'unavailable') and not is_state('switch.sonoff_dual_1', 'unknown') }}"
    online_sonoff_4ch_1:
      friendly_name: Sonoff 4CH Pro
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.sonoff_4ch_1', 'unavailable') and not is_state('switch.sonoff_4ch_1', 'unknown') }}"
    online_smartplug_1:
      friendly_name: Smart Plug 1
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.smartplug_1', 'unavailable') and not is_state('switch.smartplug_1', 'unknown') }}"
    online_smartplug_2:
      friendly_name: Smart Plug 2
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.smartplug_2', 'unavailable') and not is_state('switch.smartplug_2', 'unknown') }}"
    online_smartplug_3:
      friendly_name: Smart Plug 3
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.smartplug_3', 'unavailable') and not is_state('switch.smartplug_3', 'unknown') }}"
    online_smartplug_4:
      friendly_name: Smart Plug 4
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.smartplug_4', 'unavailable') and not is_state('switch.smartplug_4', 'unknown') }}"
    online_smartplug_5:
      friendly_name: Smart Plug 5
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.smartplug_5', 'unavailable') and not is_state('switch.smartplug_5', 'unknown') }}"
    online_smartplug_6:
      friendly_name: Smart Plug 6
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.smartplug_6', 'unavailable') and not is_state('switch.smartplug_6', 'unknown') }}"
    online_smartplug_7:
      friendly_name: Smart Plug 7
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.smartplug_7', 'unavailable') and not is_state('switch.smartplug_7', 'unknown') }}"
    online_smartplug_8:
      friendly_name: Smart Plug 8
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.smartplug_8', 'unavailable') and not is_state('switch.smartplug_8', 'unknown') }}"
    online_sonoff_rele_1:
      friendly_name: Sonoff RE5V1C 1
      icon_template: mdi:power-plug
      device_class: connectivity
      value_template: "{{ not is_state('switch.sonoff_rele_1', 'unavailable') and not is_state('switch.sonoff_rele_1', 'unknown') }}"
    home_contarina_pick_tomorrow:
      entity_id: sensor.time
      icon_template: mdi:delete-empty
      value_template: "{{ is_state_attr('sensor.ics_1', 'remaining', 1) or  is_state_attr('sensor.ics_2', 'remaining', 1) or  is_state_attr('sensor.ics_3', 'remaining', 1) or is_state_attr('sensor.ics_4', 'remaining', 1) or is_state_attr('sensor.ics_5', 'remaining', 1) }}"
    home_anyone_in:
      friendly_name: "Anyone @ Home"
      icon_template: "{% if is_state('device_tracker.cell_paolo', 'home') or is_state('device_tracker.cell_silvia', 'home') %}mdi:home-account{% else %}mdi:home-alert{% endif %}"
      value_template: "{{ is_state('device_tracker.cell_paolo', 'home') or is_state('device_tracker.cell_silvia', 'home') }}"
    irrigation_status:
      friendly_name: Stato Irrigazione
      icon_template: "{% if is_state('switch.sonoff_4ch_1', 'on') or is_state('switch.sonoff_4ch_2', 'on') or is_state('switch.sonoff_4ch_3', 'on') %}mdi:water-pump{% else %}mdi:water-pump-off{% endif %}"
      value_template: "{{ is_state('switch.sonoff_4ch_1', 'on') or is_state('switch.sonoff_4ch_2', 'on') or is_state('switch.sonoff_4ch_3', 'on') }}"

    hass_available_version:
      friendly_name: Available Version
      icon_template: mdi:home-assistant
      value_template: "{{ not is_state('sensor.hass_available_version', 'unavailable') and states('sensor.hass_available_version') != states('sensor.hass_installed_version') }}"

    hassos_available_version:
      friendly_name: OS Available Version
      icon_template: mdi:home-assistant
      value_template: "{{ not is_state('sensor.hassos_available_version', 'unavailable') and states('sensor.hassos_available_version') != states('sensor.hassos_installed_version') }}"

    hacs_updates:
      friendly_name: HACS Updates
      icon_template: hacs:hacs
      value_template: "{{ (states('sensor.hacs') | int) > 0 }}"
      attribute_templates:
        updates_count: "{{states('sensor.hacs') | int}}"

    hass_addon_updates:
      friendly_name: Addon Updates
      icon_template: mdi:cogs
      entity_id:
        - sensor.addon_adguard
        - sensor.addon_bitwarden
        - sensor.addon_dasshio
        - sensor.addon_duckdns
        - sensor.addon_nut
        - sensor.addon_nodered
        - sensor.addon_samba
        - sensor.addon_sqliteweb
        - sensor.addon_ssh
        - sensor.addon_tasmoadmin
        - sensor.addon_motioneye
        - sensor.addon_mariadb
        - sensor.addon_mosquitto
        - sensor.addon_phpmyadmin
        - sensor.addon_vscode
      value_template: >
        {%- set addon_upd = namespace(value=0) -%}
        {%- for addon in states['sensor'] if addon.name.startswith("addon_") -%}
          {% if state_attr(addon.entity_id, 'version') != state_attr(addon.entity_id, 'version_latest') %}
            {% set addon_upd.value = addon_upd.value + 1 %}
          {% endif %}
        {%- endfor -%}
        {{ (addon_upd.value | int) > 0 }}
      attribute_templates:
        updates_count: >
          {%- set addon_upd = namespace(value=0) -%}
          {%- for addon in states['sensor'] if addon.name.startswith("addon_") -%}
            {% if state_attr(addon.entity_id, 'version') != state_attr(addon.entity_id, 'version_latest') %}
              {% set addon_upd.value = addon_upd.value + 1 %}
            {% endif %}
          {%- endfor -%}
          {{ addon_upd.value }}
        # repositories: >
        #   {% set jjj = [{"name":"hacs/integration", "display_name":"HACS", "installed_version":"1.1.0", "available_version":"1.1.1"}] %}
        #   {{ jjj }}

    addon_adguard_update:
      icon_template: "{{ state_attr('sensor.addon_adguard', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_adguard', 'version') != state_attr('sensor.addon_adguard', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_adguard', 'name') }}"
        version: "{{ state_attr('sensor.addon_adguard', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_adguard', 'version_latest') }}"

    addon_bitwarden_update:
      icon_template: "{{ state_attr('sensor.addon_bitwarden', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_bitwarden', 'version') != state_attr('sensor.addon_bitwarden', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_bitwarden', 'name') }}"
        version: "{{ state_attr('sensor.addon_bitwarden', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_bitwarden', 'version_latest') }}"

    addon_dasshio_update:
      icon_template: "{{ state_attr('sensor.addon_dasshio', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_dasshio', 'version') != state_attr('sensor.addon_dasshio', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_dasshio', 'name') }}"
        version: "{{ state_attr('sensor.addon_dasshio', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_dasshio', 'version_latest') }}"

    addon_duckdns_update:
      icon_template: "{{ state_attr('sensor.addon_duckdns', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_duckdns', 'version') != state_attr('sensor.addon_duckdns', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_duckdns', 'name') }}"
        version: "{{ state_attr('sensor.addon_duckdns', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_duckdns', 'version_latest') }}"

    addon_nut_update:
      icon_template: "{{ state_attr('sensor.addon_nut', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_nut', 'version') != state_attr('sensor.addon_nut', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_nut', 'name') }}"
        version: "{{ state_attr('sensor.addon_nut', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_nut', 'version_latest') }}"

    addon_nodered_update:
      icon_template: "{{ state_attr('sensor.addon_nodered', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_nodered', 'version') != state_attr('sensor.addon_nodered', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_nodered', 'name') }}"
        version: "{{ state_attr('sensor.addon_nodered', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_nodered', 'version_latest') }}"

    addon_samba_update:
      icon_template: "{{ state_attr('sensor.addon_samba', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_samba', 'version') != state_attr('sensor.addon_samba', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_samba', 'name') }}"
        version: "{{ state_attr('sensor.addon_samba', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_samba', 'version_latest') }}"

    addon_sqliteweb_update:
      icon_template: "{{ state_attr('sensor.addon_sqliteweb', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_sqliteweb', 'version') != state_attr('sensor.addon_sqliteweb', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_sqliteweb', 'name') }}"
        version: "{{ state_attr('sensor.addon_sqliteweb', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_sqliteweb', 'version_latest') }}"

    addon_ssh_update:
      icon_template: "{{ state_attr('sensor.addon_ssh', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_ssh', 'version') != state_attr('sensor.addon_ssh', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_ssh', 'name') }}"
        version: "{{ state_attr('sensor.addon_ssh', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_ssh', 'version_latest') }}"

    addon_tasmoadmin_update:
      icon_template: "{{ state_attr('sensor.addon_tasmoadmin', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_tasmoadmin', 'version') != state_attr('sensor.addon_tasmoadmin', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_tasmoadmin', 'name') }}"
        version: "{{ state_attr('sensor.addon_tasmoadmin', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_tasmoadmin', 'version_latest') }}"

    addon_motioneye_update:
      icon_template: "{{ state_attr('sensor.addon_motioneye', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_motioneye', 'version') != state_attr('sensor.addon_motioneye', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_motioneye', 'name') }}"
        version: "{{ state_attr('sensor.addon_motioneye', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_motioneye', 'version_latest') }}"

    addon_mariadb_update:
      icon_template: "{{ state_attr('sensor.addon_mariadb', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_mariadb', 'version') != state_attr('sensor.addon_mariadb', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_mariadb', 'name') }}"
        version: "{{ state_attr('sensor.addon_mariadb', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_mariadb', 'version_latest') }}"

    addon_mosquitto_update:
      icon_template: "{{ state_attr('sensor.addon_mosquitto', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_mosquitto', 'version') != state_attr('sensor.addon_mosquitto', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_mosquitto', 'name') }}"
        version: "{{ state_attr('sensor.addon_mosquitto', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_mosquitto', 'version_latest') }}"

    addon_phpmyadmin_update:
      icon_template: "{{ state_attr('sensor.addon_phpmyadmin', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_phpmyadmin', 'version') != state_attr('sensor.addon_phpmyadmin', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_phpmyadmin', 'name') }}"
        version: "{{ state_attr('sensor.addon_phpmyadmin', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_phpmyadmin', 'version_latest') }}"

    addon_vscode_update:
      icon_template: "{{ state_attr('sensor.addon_vscode', 'icon') }}"
      value_template: "{{ state_attr('sensor.addon_vscode', 'version') != state_attr('sensor.addon_vscode', 'version_latest') }}"
      attribute_templates:
        name: "{{ state_attr('sensor.addon_vscode', 'name') }}"
        version: "{{ state_attr('sensor.addon_vscode', 'version') }}"
        version_latest: "{{ state_attr('sensor.addon_vscode', 'version_latest') }}"

- platform: mqtt  #https://www.home-assistant.io/integrations/binary_sensor.mqtt
  name: online_pzem_004t
  state_topic: "home/pzem_004t/tele/LWT"
  payload_on: "Online"
  payload_off: "Offline"

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret samsung_tv_ip
  name: online_samsung_tv
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret nas_ip
  name: online_nas_qnap
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret fritzbox_router_ip
  name: online_router_fritzbox
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret fritzbox_repeater_ip
  name: online_repeater_fritzbox
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret cell_paolo_ip
  name: online_cell_paolo
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret cell_silvia_ip
  name: online_cell_silvia
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret tablet_ale_ip
  name: online_tablet_ale
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret tablet_silvia_ip
  name: online_tablet_silvia
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret tablet_paolo_ip
  name: online_tablet_paolo
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret google_home_ip
  name: online_google_home
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret google_chromecast_ip
  name: online_google_chromecast
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret xiaomi_gateway_ip
  name: online_xiaomi_gateway
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret epson_printer_ip
  name: online_epson_printer
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret prusa_3d_printer_ip
  name: online_prusa_3d_printer
  count: 2
  scan_interval: 30

- platform: ping  #https://www.home-assistant.io/components/binary_sensor.ping
  host: !secret landroid_ip
  name: online_landroid_m141
  count: 2
  scan_interval: 30

- platform: workday  #https://www.home-assistant.io/components/binary_sensor.workday
  name: workday
  country: IT

- platform: template  #https://www.home-assistant.io/components/binary_sensor.template
  sensors:
    landroid_m141_battery_charging:
      friendly_name: M141 battery charging
      icon_template: "{{ state_attr('sensor.landroid_m141_battery', 'icon') }}"
      device_class: battery_charging
      value_template: "{{ is_state_attr('sensor.landroid_m141_battery', 'charging', 1) }}"
