- platform: template  #https://www.home-assistant.io/components/switch.template
  switches:
    event_sonoleore:
      friendly_name: "Attivo"
      icon_template: "{% if is_state('input_boolean.event_sonoleore', 'on') %}mdi:bell{% else %}mdi:bell-off{% endif %}"
      value_template: "{{ is_state('input_boolean.event_sonoleore', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.event_sonoleore
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.event_sonoleore
    event_sveglia_1:
      friendly_name: "Attivo"
      icon_template: "{% if is_state('input_boolean.event_sveglia_1', 'on') %}mdi:bell{% else %}mdi:bell-off{% endif %}"
      value_template: "{{ is_state('input_boolean.event_sveglia_1', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.event_sveglia_1
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.event_sveglia_1
    event_sveglia_2:
      friendly_name: "Attivo"
      icon_template: "{% if is_state('input_boolean.event_sveglia_2', 'on') %}mdi:bell{% else %}mdi:bell-off{% endif %}"
      value_template: "{{ is_state('input_boolean.event_sveglia_2', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.event_sveglia_2
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.event_sveglia_2
    event_sveglia_3:
      friendly_name: "Attivo"
      icon_template: "{% if is_state('input_boolean.event_sveglia_3', 'on') %}mdi:bell{% else %}mdi:bell-off{% endif %}"
      value_template: "{{ is_state('input_boolean.event_sveglia_3', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.event_sveglia_3
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.event_sveglia_3
    event_sveglia_4:
      friendly_name: "Attivo"
      icon_template: "{% if is_state('input_boolean.event_sveglia_4', 'on') %}mdi:bell{% else %}mdi:bell-off{% endif %}"
      value_template: "{{ is_state('input_boolean.event_sveglia_4', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.event_sveglia_4
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.event_sveglia_4
    event_cover_up:
      friendly_name: "Attivo"
      icon_template: "{% if is_state('input_boolean.event_cover_up', 'on') %}mdi:bell{% else %}mdi:bell-off{% endif %}"
      value_template: "{{ is_state('input_boolean.event_cover_up', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.event_cover_up
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.event_cover_up
    event_cover_down:
      friendly_name: "Attivo"
      icon_template: "{% if is_state('input_boolean.event_cover_down', 'on') %}mdi:bell{% else %}mdi:bell-off{% endif %}"
      value_template: "{{ is_state('input_boolean.event_cover_down', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.event_cover_down
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.event_cover_down


#+++++++++++++++++++++++++++++++
#+++++ Irrigation switches +++++
#+++++++++++++++++++++++++++++++
    irrigation_active:
      friendly_name: "Attivo"
      icon_template: "{% if is_state('input_boolean.irrigation_active', 'on') %}mdi:bell{% else %}mdi:bell-off{% endif %}"
      value_template: "{{ is_state('input_boolean.irrigation_active', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.irrigation_active
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.irrigation_active


#+++++++++++++++++++++++++++
#+++++ Router switches +++++
#+++++++++++++++++++++++++++
- platform: template  #https://www.home-assistant.io/components/switch.template
  switches:
    wifi_guest:
      friendly_name: Wifi Guest
      icon_template: "{% if is_state('switch.fritz_box_7530_wi_fi_mazzwifi_guest', 'on') %}mdi:wifi{% else %}mdi:wifi-off{% endif %}"
      availability_template: "{{ not is_state('switch.fritz_box_7530_wi_fi_mazzwifi_guest', 'unknown') and not is_state('switch.fritz_box_7530_wi_fi_mazzwifi_guest', 'unavailable') }}"
      value_template: "{{ is_state('switch.fritz_box_7530_wi_fi_mazzwifi_guest', 'on') }}"
      turn_on:
        service: script.wifi_guest_start
      turn_off:
        service: script.wifi_guest_stop
    wifi_24ghz:
      friendly_name: Wifi 2.4 GHz
      icon_template: "{% if is_state('switch.fritz_box_7530_wi_fi_mazzwifi', 'on') %}mdi:wifi{% else %}mdi:wifi-off{% endif %}"
      availability_template: "{{ not is_state('switch.fritz_box_7530_wi_fi_mazzwifi', 'unknown') and not is_state('switch.fritz_box_7530_wi_fi_mazzwifi', 'unavailable') }}"
      value_template: "{{ is_state('switch.fritz_box_7530_wi_fi_mazzwifi', 'on') }}"
      turn_on:
        service: script.wifi_24ghz_start
      turn_off:
        service: script.wifi_24ghz_stop
    wifi_5ghz:
      friendly_name: Wifi 5 GHz
      icon_template: "{% if is_state('switch.fritz_box_7530_wi_fi_mazzwifi_5ghz', 'on') %}mdi:wifi{% else %}mdi:wifi-off{% endif %}"
      availability_template: "{{ not is_state('switch.fritz_box_7530_wi_fi_mazzwifi_5ghz', 'unknown') and not is_state('switch.fritz_box_7530_wi_fi_mazzwifi_5ghz', 'unavailable') }}"
      value_template: "{{ is_state('switch.fritz_box_7530_wi_fi_mazzwifi_5ghz', 'on') }}"
      turn_on:
        service: script.wifi_5ghz_start
      turn_off:
        service: script.wifi_5ghz_stop
    ale_internet_timer:
      friendly_name: Ale Internet Timer
      icon_template: "{% if is_state('switch.fritzbox_7530_profile_ale', 'on') %}mdi:wifi{% else %}mdi:wifi-off{% endif %}"
      availability_template: "{{ not is_state('switch.fritzbox_7530_profile_ale', 'unknown') and not is_state('switch.fritzbox_7530_profile_ale', 'unavailable') }}"
      value_template: "{{ is_state('switch.fritzbox_7530_profile_ale', 'on') }}"
      turn_on:
        service: script.ale_internet_start
      turn_off:
        service: script.ale_internet_stop


#++++++++++++++++++++++++++++
#+++++ Tasmota switches +++++
#++++++++++++++++++++++++++++
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: sonoff_basic_1
  command_topic: "home/sonoff_basic_1/cmnd/POWER"
  state_topic: "home/sonoff_basic_1/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/sonoff_basic_1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: sonoff_basic_2
  command_topic: "home/sonoff_basic_2/cmnd/POWER"
  state_topic: "home/sonoff_basic_2/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/sonoff_basic_2/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: sonoff_basic_3
  command_topic: "home/sonoff_basic_3/cmnd/POWER"
  state_topic: "home/sonoff_basic_3/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/sonoff_basic_3/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: sonoff_dual_1
  command_topic: "home/sonoff_dual_1/cmnd/POWER1"
  state_topic: "home/sonoff_dual_1/stat/POWER1"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/sonoff_dual_1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: sonoff_dual_2
  command_topic: "home/sonoff_dual_1/cmnd/POWER2"
  state_topic: "home/sonoff_dual_1/stat/POWER2"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/sonoff_dual_1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: sonoff_4ch_1
  command_topic: "home/sonoff_4ch_1/cmnd/POWER1"
  state_topic: "home/sonoff_4ch_1/stat/POWER1"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/sonoff_4ch_1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: sonoff_4ch_2
  command_topic: "home/sonoff_4ch_1/cmnd/POWER2"
  state_topic: "home/sonoff_4ch_1/stat/POWER2"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/sonoff_4ch_1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: sonoff_4ch_3
  command_topic: "home/sonoff_4ch_1/cmnd/POWER3"
  state_topic: "home/sonoff_4ch_1/stat/POWER3"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/sonoff_4ch_1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: sonoff_4ch_4
  command_topic: "home/sonoff_4ch_1/cmnd/POWER4"
  state_topic: "home/sonoff_4ch_1/stat/POWER4"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/sonoff_4ch_1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: smartplug_1
  command_topic: "home/smart_plug_1/cmnd/POWER"
  state_topic: "home/smart_plug_1/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/smart_plug_1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: smartplug_2
  command_topic: "home/smart_plug_2/cmnd/POWER"
  state_topic: "home/smart_plug_2/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/smart_plug_2/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: smartplug_3
  command_topic: "home/smart_plug_3/cmnd/POWER"
  state_topic: "home/smart_plug_3/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/smart_plug_3/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: smartplug_4
  command_topic: "home/smart_plug_4/cmnd/POWER"
  state_topic: "home/smart_plug_4/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/smart_plug_4/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: smartplug_5
  command_topic: "home/smart_plug_5/cmnd/POWER"
  state_topic: "home/smart_plug_5/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/smart_plug_5/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: smartplug_6
  command_topic: "home/smart_plug_6/cmnd/POWER"
  state_topic: "home/smart_plug_6/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/smart_plug_6/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: smartplug_7
  command_topic: "home/smart_plug_7/cmnd/POWER"
  state_topic: "home/smart_plug_7/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/smart_plug_7/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: smartplug_8
  command_topic: "home/smart_plug_8/cmnd/POWER"
  state_topic: "home/smart_plug_8/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/smart_plug_8/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
- platform: mqtt  #https://www.home-assistant.io/components/switch.mqtt
  name: sonoff_rele_1
  command_topic: "home/sonoff_re5v1c_1/cmnd/POWER"
  state_topic: "home/sonoff_re5v1c_1/stat/POWER"
  state_on: "ON"
  state_off: "OFF"
  availability_topic: "home/sonoff_re5v1c_1/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
