#https://www.home-assistant.io/integrations/timer

ale_internet:
  name: Ale - Internet Timer
  icon: mdi:timer-outline

event_timer_off_smartplug_1:
  name: Timer Spegnimento
  icon: mdi:clock-end

event_timer_off_smartplug_2:
  name: Timer Spegnimento
  icon: mdi:clock-end

event_timer_off_smartplug_3:
  name: Timer Spegnimento
  icon: mdi:clock-end

event_timer_off_smartplug_4:
  name: Timer Spegnimento
  icon: mdi:clock-end

event_timer_off_smartplug_5:
  name: Timer Spegnimento
  icon: mdi:clock-end

event_timer_off_smartplug_6:
  name: Timer Spegnimento
  icon: mdi:clock-end

event_timer_off_smartplug_7:
  name: Timer Spegnimento
  icon: mdi:clock-end

event_timer_off_smartplug_8:
  name: Timer Spegnimento
  icon: mdi:clock-end

event_timer_off_sonoff_basic_1:
  name: Timer Spegnimento
  icon: mdi:clock-end

event_timer_off_sonoff_basic_2:
  name: Timer Spegnimento
  icon: mdi:clock-end
