#https://www.home-assistant.io/lovelace
#https://github.com/custom-cards

title: Casa Mazzini

#Include external resources
resources:
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    #https://github.com/thomasloven/lovelace-fold-entity-row
    type: module
  - url: /hacsfiles/restriction-card/restriction-card.js
    #https://github.com/iantrich/restriction-card
    type: module
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    #https://github.com/thomasloven/lovelace-card-tools
    type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    #https://github.com/thomasloven/lovelace-layout-card
    type: module
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    #https://github.com/benct/lovelace-multiple-entity-row
    type: module
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    #https://github.com/custom-cards/vertical-stack-in-card
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    #https://github.com/kalkih/mini-graph-card
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    #https://github.com/thomasloven/lovelace-auto-entities
    type: module
  - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
    #https://github.com/thomasloven/lovelace-template-entity-row
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    #https://github.com/thomasloven/lovelace-card-mod
    type: module
  - url: /hacsfiles/button-card/button-card.js
    #https://github.com/custom-cards/button-card
    type: module
  - url: /hacsfiles/battery-state-card/battery-state-card.js
    #https://github.com/maxwroc/battery-state-card
    type: module
#+++++ TEST COMPONENTS +++++
  - url: /hacsfiles/lovelace-gui-sandbox/gui-sandbox.js
    #https://github.com/thomasloven/lovelace-gui-sandbox
    type: module
  - url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
    #https://github.com/gadgetchnnel/lovelace-home-feed-card
    type: module
  - url: /hacsfiles/custom-cards/lovelace-theme-maker-master/theme-maker.js
    #https://github.com/thomasloven/lovelace-theme-maker
    type: module

button_card_templates:  #https://github.com/custom-cards/button-card
  media_button:
    styles:
      card:
        - height: 50px
      name:
        - font-size: 10px
      icon:
        - color: var(--material-primary-color)
  action_button_locked:
    color_type: icon
    styles:
      icon:
        - color: "[[[ return (entity.state == 'on' ? 'var(--material-primary-color)' : null); ]]]"
      name:
        - font-size: 12px
      card:
        - width: 80px
    lock:
      enabled: true

views:
  - !include ui_lovelace_01_main.yaml
  - !include ui_lovelace_02_devices.yaml
  - !include ui_lovelace_03_media.yaml
  - !include ui_lovelace_04_home.yaml
  - !include ui_lovelace_05_switches.yaml
  - !include ui_lovelace_06_events.yaml
  - !include ui_lovelace_07_maps.yaml
  - !include ui_lovelace_08_system.yaml
  - !include ui_lovelace_09_weather.yaml
  - !include ui_lovelace_10_other.yaml


  #+++++++++++++++++++++++
  #+++++ VIEW -> Lab +++++
  #+++++++++++++++++++++++
  - path: lab
    title: LAB
    cards:
      - type: custom:gui-sandbox  #https://github.com/thomasloven/lovelace-gui-sandbox
      - type: custom:home-feed-card  #https://github.com/gadgetchnnel/lovelace-home-feed-card
        title: Notifications
        show_empty: true
        more_info_on_tap: true
        # id_filter: ^home_feed_.*
      - type: custom:theme-maker  #https://github.com/thomasloven/lovelace-theme-maker
