#https://www.home-assistant.io/lovelace
#https://github.com/custom-cards

title: Casa Mazzini

#Include external resources
resources:
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    #https://github.com/thomasloven/lovelace-fold-entity-row
    type: js
  - url: /community_plugin/lovelace-state-switch/state-switch.js
    #https://github.com/thomasloven/lovelace-state-switch
    type: js
  - url: /community_plugin/lovelace-toggle-lock-entity-row/toggle-lock-entity-row.js
    #https://github.com/thomasloven/lovelace-toggle-lock-entity-row
    type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    #https://github.com/thomasloven/lovelace-card-tools
    type: module
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    #https://github.com/thomasloven/lovelace-layout-card
    type: js
  - url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
    #https://github.com/benct/lovelace-multiple-entity-row
    type: js
  - url: /community_plugin/custom-header/custom-header.js
    #https://github.com/maykar/custom-header
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    #https://github.com/kalkih/mini-graph-card
    type: module
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    #https://github.com/thomasloven/lovelace-auto-entities
    type: module
  - url: /community_plugin/lovelace-template-entity-row/template-entity-row.js
    #https://github.com/thomasloven/lovelace-template-entity-row
    type: module
  - url: /community_plugin/button-card/button-card.js
    #https://github.com/custom-cards/button-card
    type: module
#+++++ TEST COMPONENTS +++++

custom_header:  #https://github.com/maykar/custom-header
  # disabled_mode: true
  compact_mode: true
  hide_help: true
  hide_config: true
  voice_hide: true
  indicator_top: true
  hide_tabs: 'system'
  hidden_tab_redirect: true
  exceptions:
    - conditions:
        user: Paolo
      config:
        show_tabs: '0 to 20'

button_card_templates:  #https://github.com/custom-cards/button-card
  media_button:
    styles:
      card:
        - height: 35px
      icon:
        - color: var(--material-primary-color)

views:
  - !include ui_lovelace_01_main.yaml
  - !include ui_lovelace_02_devices.yaml
  - !include ui_lovelace_03_media.yaml
  - !include ui_lovelace_04_home.yaml
  - !include ui_lovelace_05_switches.yaml
  - !include ui_lovelace_06_events.yaml
  - !include ui_lovelace_07_maps.yaml
  - !include ui_lovelace_08_system.yaml
  - !include ui_lovelace_09_weather.yaml
  - !include ui_lovelace_10_other.yaml


  #+++++++++++++++++++++++++++++++
  #+++++ VIEW -> Test Xiaomi +++++
  #+++++++++++++++++++++++++++++++
  - path: test_xiaomi
    title: Test Xiaomi
    cards:
      - id: test_xiaomi.container
        type: custom:layout-card  #https://github.com/thomasloven/lovelace-layout-card
        layout: vertical
        max_columns: 1
        cards:
          - id: test_xiaomi.1
            type: entities  #https://www.home-assistant.io/lovelace/entities
            title: Xiaomi stuff
            show_header_toggle: false
            entities:
              - entity: light.xiaomi_hub_light
                secondary_info: last-changed
              - entity: sensor.xiaomi_hub_illumination
                secondary_info: last-changed
              - type: section
              - entity: sensor.xiaomi_humidity_1
                secondary_info: last-changed
              - entity: sensor.xiaomi_temperature_1
                secondary_info: last-changed
              - type: section
              - entity: binary_sensor.xiaomi_door_window_1
                secondary_info: last-changed
              - type: section
              - entity: binary_sensor.xiaomi_motion_1
                secondary_info: last-changed
              - entity: sensor.xiaomi_motion_1_illumination
                secondary_info: last-changed
              - entity: binary_sensor.xiaomi_motion_2
                secondary_info: last-changed
              - entity: sensor.xiaomi_motion_2_illumination
                secondary_info: last-changed
