#++++++++++++++++++++++++
#+++++ VIEW -> Main +++++
#++++++++++++++++++++++++
path: main
title: Main
icon: mdi:home-assistant
cards:
  - id: main.col1
    type: vertical-stack
    cards:
      - id: main.connected_devices
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Connected Devices
        show_header_toggle: false
        entities:
          - type: section
          - entity: binary_sensor.online_router_fritzbox
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Router
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: !secret router_url
          - entity: binary_sensor.online_repeater_fritzbox
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Repeater
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: !secret router_repeater_url
          - entity: binary_sensor.online_nas_qnap
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: NAS
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: !secret nas_url
          - entity: binary_sensor.online_adguard
            state_color: true
          - entity: binary_sensor.online_google_home_salotto
            name: Google Home Mini (Salotto)
            state_color: true
          - entity: binary_sensor.online_google_nesthub_cucina
            name: Google Nest Hub (Cucina)
            state_color: true
          - entity: binary_sensor.online_xiaomi_speaker_studio
            name: Xiaomi Smart Speaker (Studio)
            state_color: true
          - entity: binary_sensor.online_samsung_tv
            name: TV
            state_color: true
          - entity: binary_sensor.online_google_chromecast
            state_color: true
          - entity: binary_sensor.online_zigbee_gateway_1
            state_color: true
          - entity: binary_sensor.online_epson_printer
            state_color: true
          - entity: binary_sensor.online_prusa_3d_printer
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: !secret prusa_mini_url
  - id: main.col2
    type: vertical-stack
    cards:
      - id: main.mobile_devices
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Mobile Devices
        show_header_toggle: false
        entities:
          - type: section
          - entity: binary_sensor.online_cell_paolo
            state_color: true
          - entity: binary_sensor.online_cell_silvia
            state_color: true
          - entity: binary_sensor.online_tablet_paolo
            state_color: true
          - entity: binary_sensor.online_tablet_silvia
            name: Tablet Silvia (Nero)
            state_color: true
          - entity: binary_sensor.online_tablet_ale
            name: Tablet Ale (Blu)
            state_color: true
          - entity: binary_sensor.online_tablet_ale_scuola
            name: Tablet Ale (Scuola)
            state_color: true
      - id: main.batteries
        type: custom:battery-state-card  #https://github.com/maxwroc/battery-state-card
        name: Batteries
        secondary_info: last_changed
        entities:
          - entity: sensor.cell_paolo_battery
            name: Paolo's Phone
            charging_state:
              entity_id: sensor.cell_paolo_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.cell_silvia_battery
            name: Silvia's Phone
            charging_state:
              entity_id: sensor.cell_silvia_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.tablet_paolo_battery
            name: Paolo's Tablet
            charging_state:
              entity_id: sensor.tablet_paolo_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.tablet_silvia_battery
            name: Silvia's Tablet
            charging_state:
              entity_id: sensor.tablet_silvia_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
        color_thresholds:
          - value: 15
            color: Crimson
          - value: 100
            color: var(--paper-item-icon-color)
        tap_action:
          action: more-info
