#++++++++++++++++++++++++
#+++++ VIEW -> Main +++++
#++++++++++++++++++++++++
path: main
title: Main
icon: mdi:home-assistant
panel: true
cards:
  - id: main.container
    type: custom:layout-card  #https://github.com/thomasloven/lovelace-layout-card
    layout: vertical
    max_columns: 3
    cards:
      - id: main.connected_devices
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Connected Devices
        show_header_toggle: false
        entities:
          - entity: binary_sensor.online_router_fritzbox
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Router
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://fritz.box
          - entity: binary_sensor.online_repeater_fritzbox
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Repeater
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://fritz.box
          - entity: binary_sensor.online_nas_qnap
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: NAS
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://nas.local:8080
          - entity: binary_sensor.online_adguard
            state_color: true
          - entity: binary_sensor.online_google_home
            name: Google Home
            state_color: true
          - entity: binary_sensor.online_samsung_tv
            name: TV
            state_color: true
          - entity: binary_sensor.online_google_chromecast
            state_color: true
          - entity: binary_sensor.online_xiaomi_gateway
            state_color: true
          - entity: binary_sensor.online_epson_printer
            state_color: true
          - entity: binary_sensor.online_prusa_3d_printer
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://prusa-mini.local
          - entity: binary_sensor.online_pzem_004t
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://pzem-004t.local
          - entity: binary_sensor.online_sonoff_dual_1
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Serrande
            state_color: true
            icon: mdi:window-open
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://sonoff-dual-1.local
          - entity: binary_sensor.online_sonoff_4ch_1
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Irrigazione
            state_color: true
            icon: mdi:sprinkler-variant
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://sonoff-4ch.local
          - type: custom:fold-entity-row  #https://github.com/thomasloven/lovelace-fold-entity-row
            head:
              type: section
              label: Smart Plugs & Switches
            open: true
            items:
              - entity: binary_sensor.online_sonoff_basic_1
                state_color: true
              - entity: binary_sensor.online_sonoff_basic_2
                name: Sonoff Basic 2 (Tablet Paolo)
                state_color: true
              - entity: binary_sensor.online_sonoff_basic_3
                name: Sonoff Basic 3 (NAS)
                state_color: true
              - entity: binary_sensor.online_smartplug_1
                name: Smart Plug 1 (Cell. Silvia)
                state_color: true
              - entity: binary_sensor.online_smartplug_2
                state_color: true
              - entity: binary_sensor.online_smartplug_3
                state_color: true
              - entity: binary_sensor.online_smartplug_4
                state_color: true
              - entity: binary_sensor.online_smartplug_5
                state_color: true
              - entity: binary_sensor.online_smartplug_6
                state_color: true
              - entity: binary_sensor.online_smartplug_7
                state_color: true
              - entity: binary_sensor.online_smartplug_8
                state_color: true
      - break
      - id: main.mobile_devices
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Mobile Devices
        show_header_toggle: false
        entities:
          - entity: binary_sensor.online_cell_paolo
            state_color: true
          - entity: binary_sensor.online_cell_silvia
            state_color: true
          - entity: binary_sensor.online_tablet_paolo
            state_color: true
          - entity: binary_sensor.online_tablet_ale1
            name: Tablet Ale Blu
            state_color: true
          - entity: binary_sensor.online_tablet_ale2
            name: Tablet Ale Nero
            state_color: true
      - id: main.batteries
        type: custom:battery-state-card
        name: Batteries
        entities:
          - entity: sensor.cell_paolo_battery
            name: Paolo's Phone
            charging_state:
              entity_id: sensor.cell_paolo_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.cell_silvia_battery
            name: Silvia's Phone
            charging_state:
              entity_id: sensor.cell_silvia_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.tablet_paolo_battery
            name: Paolo's Tablet
            charging_state:
              entity_id: sensor.tablet_paolo_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.xiaomi_attr_battery_door_window_1
            name: Door/Window
          - entity: sensor.xiaomi_attr_battery_motion_1
            name: Motion 1
          - entity: sensor.xiaomi_attr_battery_motion_2
            name: Motion 2
          - entity: sensor.xiaomi_attr_battery_temperature_1
            name: Temperature
        color_thresholds:
          - value: 15
            color: Crimson
          - value: 100
            color: var(--paper-item-icon-color)
        collapse: 3
        tap_action:
          action: more-info
      - break
      - id: main.tools
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Tools
        show_header_toggle: false
        entities:
          - type: custom:fold-entity-row  #https://github.com/thomasloven/lovelace-fold-entity-row
            head:
              type: section
              label: Hass.io Addons
            open: true
            items:
              - type: weblink
                name: SQLite Web
                icon: mdi:database-search
                url: http://hassio:6210
              - type: weblink
                name: TasmoAdmin
                icon: mdi:z-wave
                url: http://hassio:9541
              - type: weblink
                name: Bitwarden
                icon: mdi:shield-key
                url: http://hassio:7277
          - type: custom:fold-entity-row  #https://github.com/thomasloven/lovelace-fold-entity-row
            head:
              type: section
              label: RSS Links
            open: true
            items:
              - type: weblink
                name: Raspberry Sensors
                icon: mdi:rss-box
                url: /api/rss_template/raspberry
              - type: weblink
                name: FritzBox Sensors
                icon: mdi:rss-box
                url: /api/rss_template/fritzbox
              - type: weblink
                name: Qnap Sensors
                icon: mdi:rss-box
                url: /api/rss_template/qnap
