#++++++++++++++++++++++++++
#+++++ VIEW -> System +++++
#++++++++++++++++++++++++++
path: system
title: System
icon: mdi:settings
panel: true
cards:
  - id: system.container
    type: custom:layout-card  #https://github.com/thomasloven/lovelace-layout-card
    layout: vertical
    max_columns: 3
    cards:
      - id: system.server
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Server
        show_header_toggle: false
        entities:
          - sensor.last_boot_verbose
          - sensor.cpu_temperature
          - sensor.processor_use
          - entity: sensor.memory_use
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            state_header: MB
            unit: " "
            entities:
              - entity: sensor.memory_use_percent
                name: "%"
                unit: " "
          - sensor.memory_free
          - sensor.hass_ip_address
          - type: section
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.hass_server_reboot
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.hass_server_shutdown
      - id: system.broker_mqtt
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: MQTT Broker
        show_header_toggle: false
        entities:
          - entity: sensor.mqtt_broker_version
            name: Broker
          - entity: sensor.mqtt_broker_uptime_verbose
            name: Last boot
          - entity: sensor.mqtt_broker_clients_total
            name: Clients
            state_header: Connected
          - entity: sensor.mqtt_broker_messages_received
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Messages
            state_header: Received
            entities:
              - entity: sensor.mqtt_broker_messages_retained
                name: Retained
              - entity: sensor.mqtt_broker_messages_sent
                name: Sent
          - entity: sensor.mqtt_broker_bytes_received
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Byte
            state_header: Received
            entities:
              - entity: sensor.mqtt_broker_bytes_sent
                name: Sent
      - break
      - id: system.hass
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Home Assistant
        show_header_toggle: false
        entities:
          - entity: binary_sensor.updater
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: HASS Version
            show_state: false
            state_color: true
            icon: mdi:home-assistant
            entities:
              - entity: sensor.hass_installed_version
                name: Installed
              - entity: binary_sensor.updater
                attribute: newest_version
                name: Available
          - entity: binary_sensor.hass_addon_updates
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Addon Updates
            show_state: false
            state_color: true
            entities:
              - entity: binary_sensor.hass_addon_updates
                attribute: updates_count
                unit: update(s)
                name: " "
          - entity: binary_sensor.hacs_updates
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: HACS Updates
            show_state: false
            state_color: true
            entities:
              - entity: binary_sensor.hacs_updates
                attribute: updates_count
                unit: update(s)
                name: " "
          - type: section
          - entity: sensor.hass_db_filesize
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: HASS Database
            state_header: Size
            entities:
              - entity: sensor.hass_db_states_count
                name: "States"
              - entity: sensor.hass_db_events_count
                name: "Events"
          - entity: sensor.hass_sensor_count
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: HASS Sensors 1/2
            state_header: Sensors
            entities:
              - sensor.hass_switch_count
              - sensor.hass_lights_count
          - entity: sensor.hass_automation_count
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: HASS Sensors 2/2
            state_header: Automations
            entities:
              - sensor.hass_input_count
              - sensor.hass_script_count
          - type: custom:fold-entity-row  #https://github.com/thomasloven/lovelace-fold-entity-row
            head: 
              entity: sensor.hass_addon_count
              name: Addons
              state_color: true
            items:
              - entity: sensor.addon_adguard
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: AdGuard Home
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/a0d7b954_adguard
              - entity: sensor.addon_bitwarden
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: Bitwarden RS
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/a0d7b954_bitwarden
              - entity: sensor.addon_configurator
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: File editor
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/core_configurator
              - entity: sensor.addon_dasshio
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: Dasshio
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/03d23610_dasshio
              - entity: sensor.addon_duckdns
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: Duck DNS
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/core_duckdns
              - entity: sensor.addon_motioneye
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: motionEye
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/a0d7b954_motioneye
              - entity: sensor.addon_nodered
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: Node-RED
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/a0d7b954_nodered
              - entity: sensor.addon_nut
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: Network UPS Tools
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/a0d7b954_nut
              - entity: sensor.addon_samba
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: Samba share
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/core_samba
              - entity: sensor.addon_sqliteweb
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: SQLite Web
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/a0d7b954_sqlite-web
              - entity: sensor.addon_ssh
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: SSH & Web Terminal
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/a0d7b954_ssh
              - entity: sensor.addon_tasmoadmin
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                name: TasmoAdmin
                icon: mdi:cogs
                entities:
                  - icon: mdi:open-in-new
                    tap_action: 
                      action: url
                      url_path: /hassio/addon/a0d7b954_sonweb
          - type: section
          - entity: sensor.hass_config_check_result
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Check Configuration
            show_state: false
            entities:
              - entity: script.hass_config_check_result
                toggle: true
                name: []
            secondary_info:
              entity: sensor.hass_config_check_result
              name: []
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.hass_reload_themes
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.hass_reload_customize
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.hass_reload_scripts
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.hass_reload_automations
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.hass_restart
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.hass_stop
      - break
      - id: system.configuration
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Configuration
        show_header_toggle: false
        entities:
          - entity: binary_sensor.home_anyone_in
            state_color: true
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.config_commit_to_git
              name: Commit config to Git (HA-Config-Live)
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.snapshot_full_create
          - type: custom:restriction-card  #https://github.com/iantrich/restriction-card
            row: true
            card:
              entity: script.hass_recorder_purge
      - id: system.commands
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Commands
        show_header_toggle: false
        entities:
          - input_select.home_mode
          - input_select.hass_theme_selected
      - id: system.github
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: GitHub Repos
        show_header_toggle: false
        entities:
          - entity: sensor.github_1
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: HomeAssistant-Config
            show_state: false
            icon: mdi:github-circle
            entities:
              - attribute: html_url
                icon: mdi:open-in-new
                tap_action:
                  action: url
                  url_path: https://github.com/pmazz/HomeAssistant-Config
              - entity: sensor.github_1_commits
                name: Commits
              - attribute: stargazers_count
                name: Stars
              - attribute: subscribers_count
                name: Watchers
              - attribute: forks_count
                name: Forks
          - entity: sensor.github_2
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: ps_hassio_entities
            show_state: false
            icon: mdi:github-circle
            entities:
              - attribute: html_url
                icon: mdi:open-in-new
                tap_action:
                  action: url
                  url_path: https://github.com/pmazz/ps_hassio_entities
              - entity: sensor.github_2_commits
                name: Commits
              - attribute: stargazers_count
                name: Stars
              - attribute: subscribers_count
                name: Watchers
              - attribute: forks_count
                name: Forks
