#++++++++++++++++++++++++++
#+++++ VIEW -> Events +++++
#++++++++++++++++++++++++++
path: events
title: Events
icon: mdi:calendar-clock
cards:
  - id: events.col1
    type: vertical-stack
    cards:
      - id: events.today
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Today
        show_header_toggle: false
        entities:
          - type: section
          - entity: sensor.date
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Date/Time
            show_state: false
            entities:
              - entity: sensor.weekday
                name: Weekday
              - entity: sensor.date
                name: Date
              - entity: sensor.time
                name: Time
          - entity: binary_sensor.workday
            state_color: true
      - id: events.contarina
        type: custom:auto-entities
        card:
          type: entities  #https://www.home-assistant.io/lovelace/entities
          title: Contarina
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.ics_*"
              options:
                type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
                secondary_info:
                  attribute: remaining
                  name: tra
                  unit: gg
        sort:
          method: attribute
          attribute: remaining
          numeric: true
      - id: events.sono_le_ore
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Avviso Orario
        show_header_toggle: false
        entities:
          - type: section
          - entity: input_boolean.event_sonoleore
            state_color: true
          - input_select.event_type_sonoleore
          - input_number.event_volume_sonoleore
  - id: events.col2
    type: vertical-stack
    cards:
      - id: events.sveglia3
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Avviso 1
        show_header_toggle: false
        entities:
          - type: section
          - entity: switch.event_sveglia_3
            state_color: true
          - input_datetime.event_sveglia_3
          - input_text.event_sveglia_3
          - input_number.event_volume_sveglia_3
          - input_select.event_daytype_sveglia_3
          - input_select.event_homemode_sveglia_3
      - id: events.sveglia4
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Avviso 2
        show_header_toggle: false
        entities:
          - type: section
          - entity: switch.event_sveglia_4
            state_color: true
          - input_datetime.event_sveglia_4
          - input_text.event_sveglia_4
          - input_number.event_volume_sveglia_4
          - input_select.event_daytype_sveglia_4
          - input_select.event_homemode_sveglia_4
  - id: events.col3
    type: vertical-stack
    cards:
      - id: events.sveglia1
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Sveglia 1
        show_header_toggle: false
        entities:
          - type: section
          - entity: switch.event_sveglia_1
            state_color: true
          - input_datetime.event_sveglia_1
          - input_text.event_sveglia_1
          - input_number.event_volume_sveglia_1
          - input_select.event_daytype_sveglia_1
          - input_select.event_homemode_sveglia_1
      - id: events.sveglia2
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Sveglia 2
        show_header_toggle: false
        entities:
          - type: section
          - entity: switch.event_sveglia_2
            state_color: true
          - input_datetime.event_sveglia_2
          - input_text.event_sveglia_2
          - input_number.event_volume_sveglia_2
          - input_select.event_daytype_sveglia_2
          - input_select.event_homemode_sveglia_2
