#++++++++++++++++++++++++
#+++++ VIEW -> Main +++++
#++++++++++++++++++++++++
path: main
title: Main
icon: mdi:home-assistant
panel: true
cards:
  - id: main.container
    type: custom:layout-card  #https://github.com/thomasloven/lovelace-layout-card
    layout: vertical
    max_columns: 2
    cards:
      - id: main.connected_devices
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Connected Devices
        show_header_toggle: false
        entities:
          - type: section
          - entity: binary_sensor.online_router_fritzbox
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Router
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://fritz.box
          - entity: binary_sensor.online_repeater_fritzbox
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: Repeater
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://fritz.box
          - entity: binary_sensor.online_nas_qnap
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            name: NAS
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://nas.local:8080
          - entity: binary_sensor.online_adguard
            state_color: true
          - entity: binary_sensor.online_google_home
            name: Google Home
            state_color: true
          - entity: binary_sensor.online_samsung_tv
            name: TV
            state_color: true
          - entity: binary_sensor.online_google_chromecast
            state_color: true
          - entity: binary_sensor.online_xiaomi_gateway
            state_color: true
          - entity: binary_sensor.online_epson_printer
            state_color: true
          - entity: binary_sensor.online_prusa_3d_printer
            type: custom:multiple-entity-row  #https://github.com/benct/lovelace-multiple-entity-row
            state_color: true
            entities:
              - icon: mdi:open-in-new
                tap_action: 
                  action: url
                  url_path: http://prusa-mini.local
      - break
      - id: main.mobile_devices
        type: entities  #https://www.home-assistant.io/lovelace/entities
        title: Mobile Devices
        show_header_toggle: false
        entities:
          - type: section
          - entity: binary_sensor.online_cell_paolo
            state_color: true
          - entity: binary_sensor.online_cell_silvia
            state_color: true
          - entity: binary_sensor.online_tablet_paolo
            state_color: true
          - entity: binary_sensor.online_tablet_ale
            name: Tablet Ale (Blu)
            state_color: true
          - entity: binary_sensor.online_tablet_silvia
            name: Tablet Silvia (Nero)
            state_color: true
      - id: main.batteries
        type: custom:battery-state-card  #https://github.com/maxwroc/battery-state-card
        name: Batteries
        secondary_info: last_changed
        entities:
          - entity: sensor.cell_paolo_battery
            name: Paolo's Phone
            charging_state:
              entity_id: sensor.cell_paolo_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.cell_silvia_battery
            name: Silvia's Phone
            charging_state:
              entity_id: sensor.cell_silvia_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.tablet_paolo_battery
            name: Paolo's Tablet
            charging_state:
              entity_id: sensor.tablet_paolo_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.tablet_silvia_battery
            name: Silvia's Tablet
            charging_state:
              entity_id: sensor.tablet_silvia_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.xiaomi_attr_battery_door_window_1
            name: Door/Window
        color_thresholds:
          - value: 15
            color: Crimson
          - value: 100
            color: var(--paper-item-icon-color)
        collapse: 4
        tap_action:
          action: more-info
