#+++++++++++++++++++++++++++++++
#+++++ VIEW -> Other Stuff +++++
#+++++++++++++++++++++++++++++++
path: other
title: Other Stuff
icon: mdi:alien
cards:
  - id: other.col1
    type: vertical-stack
    cards: []
