- name: !secret zone_home_name
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  radius: 100
  icon: mdi:home-circle

- name: !secret zone_workpaolo_name
  latitude: !secret zone_workpaolo_lat
  longitude: !secret zone_workpaolo_long
  radius: 100
  icon: mdi:briefcase

- name: !secret zone_worksilvia_name
  latitude: !secret zone_worksilvia_lat
  longitude: !secret zone_worksilvia_long
  radius: 100
  icon: mdi:briefcase

- name: !secret zone_grandparents_name
  latitude: !secret zone_grandparents_lat
  longitude: !secret zone_grandparents_long
  radius: 100
  icon: mdi:account-multiple
